---
title: "Objectives"
author: "Kevin Gilds, MPA"
date: "November 27, 2016"
output: html_document
---

# Objectives of the Get REAL! Program 

## Reading Improvement:

* 50% of participating students will improve their reading skills as demonstrated by their Language Arts grade increasing or maintaining a "C" grade from the baseline grading period to the final grading period as evidenced by report cards/school reports.


## Improved Attendance:

* 60% of participating students will either maintain or improve their attendance rates as demonstrated by their decreased absences from the baseline grading period to the final grading period as evidenced by report cards/school reports.

## Improvement In School Behavior

* 70% of participating students will show improvement in behavior by decreasing their number of suspensions from the baseline grading period to final grading period or not having a suspension during the school year as evidenced from the student's report card/school reports.

## Improved Life Skills

* 70% of participating girls will demonstrate an increased understanding of pertinent life skills as demonstrated by a pre and post assessment

