---
title: "Get Real Enrollment"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(sqldf)
library(plotly)

library(leaflet)
library(tidyverse)

setwd("~/GitHub/getReal20162017/special projects")


council <- read_csv("coor.csv")
```
`
```{r}
library(DT)
library(getREAL)
library(dplyr)
library(pander)
library(ggplot2)
library(effsize)
library(knitr)
library(catspec)

```




Councils and Enrollment
=====================================  


Row
------------------------------------

### Girl Scout Councils Across Florida

```{r}
leaflet(data = council) %>% addTiles() %>%
  addMarkers(~long, ~lat, popup = ~as.character(council))
```


Row {.tabset .tabset-fade}
-------------------------

### Enrollment Data

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")

enrollment <- dbReadTable(getReal_2016db, "enrollment_view")

enrollment <- enrollment %>%
    filter(time == "01/13/2017")

enrollment <- enrollment %>%
    select(4:7, 9)
    
enrollment <- enrollment[, c(5,1:4)]



enrollment_total <-enrollment %>%
    rename(council = council_name)%>%
    group_by(council)%>%
    summarise(Total = sum(Total))


enrollment_total$council <- factor(enrollment_total$council, levels =enrollment_total$council[order(enrollment_total$Total)])



#enrollment_total

enrollment_2 <- enrollment
#total <-colSums(enrollment_2)

#total

#enroll<-ggplot(enrollment_total, aes(factor(council),y=Total)) + geom_bar(stat = "identity")


#enroll

enroll_p <- plot_ly(enrollment_total, x=~council, y = ~Total, type = 'bar')


enroll_p



```

### Enrollment Table
```{r}
kable(enrollment_2)
```



Monthly Attendance{data-orientation=columns}
=====================================  
Row {data-height=600}
------------------------------

```{r}
students_served <- dbReadTable(getReal_2016db, "students_served2")

students_s <- students_served %>%
    group_by(date)%>%
    summarise(students_served =sum(students_served))



#students_served <- ggplot(students_served, aes( x= date, y=students_served)) + geom_bar(stat = "identity") 



#students_served <- ggplotly(students_served)

ss <- plot_ly(students_s, x= ~date, y = ~students_served)


ss




```

column {data-height=600}
------------------------------

```{r}
sh <- students_served %>%
    group_by(date)%>%
    summarise(sessions_held =sum(sessions_held))

sh_p <- plot_ly(sh, x =~date, y = ~sessions_held)

sh_p
```




    