---
title: "langarts_data"
author: "Kevin Gilds, MPA"
date: "April 9, 2017"
output: github_document
---


```{r reading_import_libaries, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(pander)
library(ggplot2)
library(sqldf)
library(knitr)
library(reshape2)
library(getREAL)

```


```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

### Make connection with database
getRealdb<- dbConnect(SQLite(), dbname="outcome_history.sqlite")

q1_langarts <- dbReadTable(getRealdb,"Q1_langarts_1617") # read the table

q2_langarts <- dbReadTable(getRealdb, "Q2_langarts_1617") # read the table to object

q3_langarts <- dbReadTable(getRealdb, "Q3_langarts_1617") # read the table to object

dim(q1_langarts)

dim(q2_langarts)

```



```{r}

#students <- with(q1_reading, tapply(girl_code, reading_pts, mean))

#for every grading period bring it down to a single grade point with average and add Time Variable 

q1_lang_avg <- aggregate(lang_pts ~ girl_code + council, data = q1_langarts, mean)

q1_lang_avg_s <- q1_lang_avg %>%
    mutate("Time" = "Q1")

q2_lang_avg <- aggregate(lang_pts ~ girl_code + council, data = q2_langarts, mean)

q2_lang_avg_s <- q2_lang_avg %>%
    mutate("Time" = "Q2")

q3_lang_avg <-aggregate(lang_pts ~ girl_code + council, data= q3_langarts, mean)

q3_lang_avg_s <- q3_lang_avg %>%
    mutate("Time" = "Q3")

```

# Start Q1 Run
## Match Q1-Q3
```{r}
#Merge matching girl Code data from Q1 to Q3; rename variables to human readable form; select variables of interest
q1q3 <- inner_join(q1_lang_avg_s,q3_lang_avg_s, by="girl_code") %>%
    rename(council = council.x) %>%
    rename(baseline = lang_pts.x) %>%
    rename(data_source_1 = Time.x) %>%
    rename(final = lang_pts.y) %>%
    rename(data_source_2 = Time.y)%>%
    select(1:4,6:7)

head(q1q3)

dim(q1q3)
```

# No Matches Q1-Q3
```{r}

#Find students where there is not match between Q1-Q3; to see if there is a match somewhere else
no_q1q3 <- anti_join(q1_lang_avg_s, q3_lang_avg_s, by="girl_code")

head(no_q1q3)

dim(no_q1q3)

```

# Joins No Matches from Q1-Q3 to Q2
```{r}

#Try to match students who did not match in Q1-Q3 to Q2. This will find matches between Q1-Q2 where there was no match between Q1-Q3
q1q2 <- inner_join(no_q1q3, q2_lang_avg_s, by="girl_code") %>%
    rename(council = council.x) %>%
    rename(baseline = lang_pts.x) %>%
    rename(data_source_1 = Time.x) %>%
    rename(final = lang_pts.y) %>%
    rename(data_source_2 = Time.y)%>%
    select(1:4,6:7)



```

# End Q1 run
##No matches Q1-Q3-Q2

```{r}

# Finds cases where there was no match between Q1-Q2 or Q3
no_matches <- anti_join(no_q1q3, q2_lang_avg_s, by="girl_code")

dim(no_matches)

head(no_matches)
```

#Matches to Q1
```{r}
q1_run <- rbind(q1q3, q1q2)

dim(q1_run)

head(q1_run)

```

# Start Q2 Run: Match Q2-Q3
```{r}
#Merge matches between Students in Quarter 2 and Quarter 3
q2q3 <- inner_join(q2_lang_avg_s, q3_lang_avg_s, by="girl_code")



```

# Q2 Run 
```{r}
#Because Q1 is the priority match; this code will select those that are not already in the Q1 run
q2_run <- anti_join(q2q3, q1_run, by="girl_code")%>%
    rename(council = council.x) %>%
    rename(baseline = lang_pts.x) %>%
    rename(data_source_1 = Time.x) %>%
    rename(final = lang_pts.y) %>%
    rename(data_source_2 = Time.y)%>%
    select(1:4,6:7)


dim(q2_run)
```



# Merge Q1 Run and Q2 Run
```{r}
#Merge the Q1 Run and Q2 Run
q1_q2_run <- rbind(q1_run, q2_run)

dim(q1_q2_run)

```

# Save data to RDs

```{r}
setwd("~/GitHub/getReal20162017/Report Scripts/langarts")

kable(q1_q2_run)

saveRDS(q1_q2_run, "langarts.Rds")
```






```{r}
q1_q2_run_t <- q1_q2_run %>%
    summarise(n_distinct(girl_code))

q1_q2_run_t
```


```{r}
q3_test <- rbind(q1_lang_avg_s, q2_lang_avg_s)

q3_test <- rbind(q3_test,q3_lang_avg_s)


head(q3_test)
```











```{r eval=FALSE}

lang_arts_comparisons <- inner_join(q2_lang_avg, q1_lang_avg, by="girl_code")




```



```{r eval=FALSE}
lang_arts_comparisons <- lang_arts_comparisons %>%
    rename(Q2_Avg = lang_pts.x)%>%
    rename(Q1_Avg = lang_pts.y)%>%
    rename(council = council.x)%>%
    mutate(diff = Q2_Avg - Q1_Avg)%>%
    mutate("Data_Source" = "Q2-Q1")

dim(lang_arts_comparisons)

head(lang_arts_comparisons)

```

