---
title: "q1_dm"
output:
  html_document: default
  html_notebook: default
---

### Set working directory, library, and read raw data (needs updated data)


```{r q1_library}
library(tidyverse) #load tidy package
library(sqldf)
library(pander)

```
.
```{r q1_read_data}
q1_data <- readRDS("q1_data.Rds")


#names(q1_data)



```

```{r q1_colnames}

#change column names averages
colnames (q1_data)[7] <- "reading_avg"
colnames (q1_data)[10] <- "lang_avg"

# change column names demographics
colnames (q1_data)[13] <- "council"
colnames (q1_data)[14] <- "girl_code"
colnames (q1_data)[15] <- "school"
colnames (q1_data)[16] <- "enrolled"

# Attendance and Behavior
colnames (q1_data)[18] <- "unexcused"
colnames (q1_data)[19] <- "excused"
colnames (q1_data)[20] <- "in_school"
colnames (q1_data)[21] <- "out_school"
colnames (q1_data)[22] <- "expelled"
colnames (q1_data)[23] <- "Nothing"


# Reading 
colnames (q1_data)[25] <- "M/J INTENS READ"
colnames (q1_data)[26] <- "M/J READ 1"
colnames (q1_data)[27] <- "M/J READ 1, ADV"
colnames (q1_data)[28] <- "M/J READ 2"
colnames (q1_data)[29] <- "M/J READ 2, ADV"
colnames (q1_data)[30] <- "M/J READ 3"
colnames (q1_data)[31] <- "M/J READ3, ADV"
colnames (q1_data)[32] <- "free_reading1"
colnames (q1_data)[33] <- "free_reading2"
colnames (q1_data)[34] <- "M/J DE LA ESOL-READ"

# change colnmaes lang arts section
colnames (q1_data)[36] <- "M/J LANG ARTS 1 ESOL"
colnames (q1_data)[37] <- "M/J LANG ARTS 2 ESOL"
colnames (q1_data)[38] <- "M/J LANG ARTS 3 ESOL"
colnames (q1_data)[39] <- "M/J DEVELOPMENTAL  LANG ARTS ESOL"
colnames (q1_data)[40] <- "M/J LANG ARTS 1"
colnames (q1_data)[41] <- "M/J LANG ARTS 1 ADV"
colnames (q1_data)[42] <- "M/J LANG ARTS 2"
colnames (q1_data)[43] <- "M/J LANG ARTS 2 ADV"
colnames (q1_data)[44] <- "M/J LANG ARTS 3"
colnames (q1_data)[45] <- "M/J LANG ARTS 3 ADv"
colnames (q1_data)[46] <- "M/J ENG 2 CAMB SEC 2"
colnames (q1_data)[47] <- "M/J IB MYP LANG LIT 1"
colnames (q1_data)[48] <- "M/J ENG 1 CAMB SEC 1"
colnames (q1_data)[49] <- "M/J IB MYP LANG & LIT 3"
colnames (q1_data)[50] <- "M/J IB MYP LANG & LIT 2"
colnames (q1_data)[51] <- "M/J ENG 3 CAMB SEC 3"
colnames (q1_data)[52] <- "M/J INTENS LANG ARTS"
colnames (q1_data)[53] <- "free_lang1"
colnames (q1_data)[54] <- "free_lang2"
colnames (q1_data)[55] <- "M/J LANG ARTS TRAN"
colnames (q1_data)[56] <- "M/J DE LANG ARTS ESOL"
colnames (q1_data)[57] <- "blankspace"

names(q1_data)

```


```{r q1_data_clean}




q1_data$girl_code <- as.character(q1_data$girl_code)

### Make all girCode to upper case for matching
q1_data$girl_code <- toupper(q1_data$girl_code)



q1_data <- q1_data %>%
    filter(Finished ==1)

#pander(table(q1_data$girl_code)) #test for duplicate girl codes

```


```{r clean_council_names}

q1_data$council <-sub("Girl Scouts of the Gateway Council", "Gateway Council", fixed=TRUE, q1_data$council)

q1_data$council <-sub("Girl Scouts of Citrus Council", "Citrus Council", fixed=TRUE, q1_data$council)

q1_data$council <-sub("Girl Scouts of Southeast Florida", "Southeast Council", fixed=TRUE, q1_data$council)

q1_data$council <-sub("Girl Scout Council of Tropical Florida", "Tropical Council", fixed = TRUE, q1_data$council)

q1_data$council <-sub("Girl Scouts of West Central Florida", "West Central Council", fixed = TRUE, q1_data$council)

q1_data$council <-sub("Girl Scout Council of the Panhandle", "Panhandle Council", fixed = TRUE, q1_data$council)


```


```{r q1_data_unique}

q1_data <- q1_data[!(duplicated(q1_data$girl_code) | duplicated(q1_data$girl_code, fromLast = TRUE)), ]  #find and extract unique cases

dim(q1_data)

#pander(table(q1_data$girl_code)) #test for duplicate girl codes

#preUnique<- pre [!(duplicated(pre$girlCode) | duplicated(pre$girlCode, fromLast = TRUE)), ]

#dim(preUnique)


```





```{r q1_dupes}

q1Dupes <- duplicated(q1_data$girl_code) | duplicated(q1_data$girl_code, fromLast=TRUE)


#preDupes <-duplicated(pre$girlCode) | duplicated(pre$girlCode, fromLast=TRUE)

#preDupes <-pre[preDupes, ]

#dim(preDupes)



### Subset the duplicates
q1Dupes <-q1_data[q1Dupes, ]


q1Dupes

```





# Attendance: 

```{r q1_attendance}
q1_attendance <- q1_data %>%
    select(13:16,18:19)  #take columns of interest



q1_attendance$unexcused[which(is.na(q1_attendance$unexcused))] <- 0
q1_attendance$excused[which(is.na(q1_attendance$excused))] <-0


q1_attendance <- q1_attendance %>%
        mutate("total" = unexcused + excused)


which(is.na(q1_attendance$total))

mean(q1_attendance$total)


```



# Behavior

```{r q1_behavior}
q1_behavior <- q1_data %>%
    select(13:16, 20:21)  #take columns of interest
    
    
q1_behavior$in_school[which(is.na(q1_behavior$in_school))] <- 0  #find na and replace with 0
q1_behavior$out_school[which(is.na(q1_behavior$out_school))] <-0  #find na values and replace with 0

q1_behavior <- q1_behavior %>%   
    mutate("total"= in_school + out_school) #calculate total 
    
head(q1_behavior) #check work

which(is.na(q1_behavior$total))

mean(q1_behavior$total)

```

# Expelled

```{r q1_expelled}
q1_expelled <- q1_data %>%
    select(13:16, 22) #take columns of interest

head(q1_expelled)
```



# Reading



```{r q1_reading}
q1_reading <- q1_data %>%
    gather("reading_course", "Grade",25:31, 34) %>% #gather reading columns and put them in row
    select(7,13:16, 50:51) #select reading columns
    

names(q1_reading)

dim(q1_reading)

q1_reading <-na.omit(q1_reading) #get rid of cases with no data




dim(q1_reading)

q1_reading



```



```{r q1_freereading}
q1_freereading <- q1_data %>%
    select(7,13:16, 32:33) #select free enter
    
q1_freereading <- q1_freereading[,c(1,2,3,4,5,7,6)] #re-arrange columns to make them align with q1 readind df

q1_freereading <- q1_freereading %>%
    rename("reading_course" = free_reading2) %>% #rename to match q1_reading
    rename("Grade" = free_reading1) #rename to match q1_reading
    

dim(q1_freereading)
q1_freereading <- na.omit(q1_freereading) #clean up to find cases with data



dim(q1_freereading)

q1_freereading


```


```{r q1_free, }

q1_freereading <- q1_freereading[grep("READ", q1_freereading$reading_course, ignore.case=TRUE, fixed=TRUE),]

q1_freereading

```



```{r q1_reading_bind}

q1_reading <- rbind(q1_reading, q1_freereading) #bind main q1_reading and free text

dim(q1_reading)

q1_reading

which(is.na(q1_reading$Grade))

```


```{r clean_up_reading}

q1_reading <- q1_reading %>%
    filter(Grade != "Did not mean to select this course")



```

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/west_central_council")


q1_reading_test <- q1_reading %>%
    filter(girl_code == "320ZB062105")


write.csv(q1_reading_test, file="reading_course_question.csv", row.names=FALSE)
```

### Reading Points

```{r reading_pts, echo=FALSE}

reading_pts <- numeric(0)

for(i in q1_reading$Grade){

     reading_pts<- c(reading_pts,switch(i, "A" =4, "B"=3, "C"=2, "D"=1, "F"=0))

     reading_pts
     
}

q1_reading <-cbind(q1_reading, reading_pts)

q1_reading

```



# Language Arts

```{r q1_langarts}
q1_langarts <- q1_data %>% 
    gather("langarts_course", "grade", 36:52,55:56)%>% #put lang arts classes in rows
    select(10, 13:16, 39:40) #select lang arts courses and grades

names(q1_langarts)

q1_langarts <- na.omit(q1_langarts) #get rid of cases with no entry

q1_langarts
```

```{r}
q1_freelang <- q1_data %>%
    select(10, 13:16,53:54) #find free entry lang cases

names(q1_freelang)

q1_freelang <- q1_freelang[,c(1,2,3,4,5,7,6)] #rearrange columns to match regular lang courses 



table(q1_freelang$free_lang1, q1_freelang$free_lang2) #check for data

q1_freelang <- q1_freelang %>%
    rename("langarts_course" = free_lang2) %>% #rename columns to match reg lang courses
    rename("grade" = free_lang1)



names(q1_freelang)


```

```{r grep_lang, echo=FALSE}


q1_freelang_english <- q1_freelang[grep("ENGLISH", q1_freelang$langarts_course, ignore.case=TRUE, fixed=TRUE),]

q1_freelang_english

names(q1_freelang_english)

```

```{r bind_q1_free}

q1_langarts <- rbind(q1_langarts, q1_freelang_english)





```


```{r filter_mistake}

q1_langarts <- q1_langarts %>%
    filter(grade != "Did not mean to select this course")


dim(q1_langarts)

which(is.na(q1_langarts$grade))

```


## Languge Points

```{r lang_pts}
lang_pts <- numeric(0)

for(i in q1_langarts$grade){

     lang_pts<- c(lang_pts,switch(i, "A" =4, "B"=3, "C"=2, "D"=1, "F"=0))

     lang_pts
}

q1_langarts <-cbind(q1_langarts, lang_pts)

q1_langarts

```



# Join All Behavior Data

```{r}
q1_behavior_data <- full_join(q1_behavior, q1_attendance, by="girl_code")

dim(q1_behavior_data)
head(q1_behavior_data)
names(q1_behavior_data)

q1_behavior_data <- q1_behavior_data %>%
    select(1,2,3,4, 5, 7, 13) %>%
    rename(council = council.x) %>%
    rename(school = school.x) %>%
    rename(enrolled = enrolled.x) %>%
    rename(suspension_total = total.x)%>%
    rename(absences_total = total.y)

head(q1_behavior_data)

```



```{r combine_expelled}

q1_behavior_data <- full_join(q1_behavior_data, q1_expelled, by="girl_code")

names(q1_behavior_data)

q1_behavior_data <- q1_behavior_data %>%
    select(1, 2, 3, 4, 6,7,11) %>%
    rename(council = council.x) %>%
    rename(school = school.x)%>%
    rename(enrolled = enrolled.x)
    #rename(expelled = expelled.x)


head(q1_behavior_data)
    

```



#Combine Grades

```{r combine_grades}
q1_grades_c <- full_join(q1_reading, q1_langarts, by="girl_code")

names(q1_grades_c)

q1_grades_c <- q1_grades_c %>%
    select(2,6,7,12,13) %>%
    rename(council = council.x)

head(q1_grades_c)

```


```{r "sq1_sqlite", root.dir= "C:/Users/kevin/Dropbox/GetReal/Data/sqlite" }

setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")


getReal_db<- dbConnect(SQLite(), dbname="outcome_history.sqlite") #established connection with database

dbWriteTable(conn =getReal_db, name= "Q1_attendance_1617", value= q1_attendance, row.names=FALSE, overwrite=TRUE)

dbWriteTable(conn =getReal_db, name= "Q1_behavior_1617", value= q1_behavior, row.names=FALSE, overwrite=TRUE)

dbWriteTable(conn =getReal_db, name= "Q1_expelled_1617", value= q1_expelled, row.names=FALSE, overwrite=TRUE)

dbWriteTable(conn =getReal_db, name= "Q1_reading_1617", value= q1_reading, row.names=FALSE, overwrite=TRUE)

dbWriteTable(conn =getReal_db, name= "Q1_langarts_1617", value= q1_langarts, row.names=FALSE, overwrite=TRUE)

dbWriteTable(conn =getReal_db, name= "Q1_duplicates_1617", value= q1Dupes, row.names=FALSE, overwrite=TRUE)

dbWriteTable(conn =getReal_db, name= "Q1_behavior_data_1617", value= q1_behavior_data, row.names=FALSE, overwrite=TRUE)



```


# Functions
```{r grade_file_function}


grades_file <- function(x) {
    grade_file <- filter(q1_grades_c, council == x)
    write.csv (grade_file, file="grade_file_q1.csv", row.names=FALSE)
    
    
}


```

```{r behavior_function}

behavior_file <- function(x){
    behavior_file <- filter(q1_behavior_data, council== x)
    write.csv(behavior_file, file="behavior.file_q1.csv", row.names=FALSE)

    }

```

```{r q1_duplicate_function}

grade_dupes_file <-function(x){
    grade_dupes <-filter(q1Dupes, council== x)
    write.csv(grade_dupes, file="grade_dupes_q1.csv", row.names=FALSE)
    
}

```



### Citrus Council
```{r make_student}

setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/citrus_council")


grades_file("Citrus Council")

behavior_file("Citrus Council")

grade_dupes_file("Citrus Council")

```


### Gateway Council

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/gateway_council")

grades_file("Gateway Council")

behavior_file("Gateway Council")

grade_dupes_file("Gateway Council")



```


### Southeast Council
```{r}

setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/southeast")


grades_file("Southeast Council")

behavior_file("Southeast Council")

grade_dupes_file("Southeast Council")


```


### Tropical Council

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/tropical_council")

grades_file("Tropical Council")

behavior_file("Tropical Council")

grade_dupes_file("Tropical Council")

```


### Panhandle Council

```{r}

setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/panhandle_council")

grades_file("Panhandle Council")

behavior_file("Panhandle Council")

grade_dupes_file("Panhandle Council")



```

### West Central Council

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/west_central_council")

grades_file("West Central Council")

behavior_file("West Central Council")

grade_dupes_file("West Central Council")



```
=======



