---
title: "langarts_report"
author: "Kevin Gilds, MPA"
date: "May 13, 2017"
output: html_document
---

```{r lang_libraries}
library(dplyr)
library(pander)
library(getREAL)
library(knitr)
library(formattable)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r read_lang_dat}
langarts<-readRDS("langarts.RDS")

langarts <- langarts %>%
    mutate(pt_diff = final- baseline)


dim(langarts)#test your #

```

```{r display_raw_lang}
kable(langarts)
```


```{r lang_success_fun }
success <-lang_success()
```


```{r lang_success}
lang_success <- langarts %>%
    filter(final >=2, pt_diff >=0)%>% #filter those with C and increased/maineded their grade.
    mutate("Success" = "TRUE") #add variable that they had success. 

dim(lang_success)

```


```{r lang_not_success}
lang_success_n <- langarts %>%
    filter(final >=2, pt_diff  < 0) %>% #filter those that had final higer than C but decreased grade.
    mutate("Success" = "FALSE") #add variable false

lang_success_x <- langarts %>%  #filter 
    filter(final < 2) %>%
    mutate("Success" = "FALSE")

lang_f <- rbind(lang_success_n, lang_success_x)

dim(lang_f)


```


## Counts

```{r}
increased <- langarts %>%
    filter(final >=2, pt_diff >0)

increased<-nrow(increased)

maintain <- langarts %>%
    filter(final >=2, pt_diff ==0)

maintain<-nrow(maintain)



success_table <- data.frame(increased, maintain)

kable(success_table)

fail_topass <- langarts %>%
    filter(baseline < 2, final >=2)

nrow(fail_topass)

```





```{r merge_lang}
langarts <- rbind(lang_success, lang_f)

dim(langarts)
```

```{r mean_lang_pt}
lang_pt <- langarts %>%
    summarise(Avg =mean(pt_diff))

lang_pt
```



```{r table_succes}
lang_success <- langarts %>%
    count(Success) %>%
    mutate(percent = n /sum(n))
    
lang_success$percent <- percent(lang_success$percent)



kable(lang_success)
```



```{r council_success}
lang_success_c <- langarts %>%
    group_by(council) %>%
    count(Success) %>%
    mutate(percent = n /sum(n))
    
lang_success_c$percent <- percent(lang_success_c$percent)

lang_success_c <- lang_success_c %>%
    filter(Success ==TRUE)


kable(lang_success_c)
```

