---
title: "attendance"
author: "Kevin Gilds, MPA"
date: "December 8, 2016"
output: html_document
---
```{r attendance_libaries, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(pander)
library(ggplot2)
library(sqldf)
library(psych)
library(knitr)
library(gridExtra)
library(effsize)
library(likert)
library(getREAL)

```


```{r attendance_db, echo=FALSE}

setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

### Make connection with database
getRealdb <- dbConnect(SQLite(), dbname="outcome_history.sqlite")


q1_attendance <- dbReadTable(getRealdb,"Q1_attendance_1617")

```

# Decrease in Absenteeism

## Objective

* Objective: 60% of participating students will either maintain or improve their attendance 
rates as demonstrated by their decreased absences from the baseline grading period to the final grading period as evidenced by report cards/school reports.*


```{r q1_attendance_mean, echo=FALSE}

q1_attendance$total <- as.numeric(q1_attendance$total)




```


```{r q1_absences_tbl, echo=FALSE}

q1_absences <-with(q1_attendance,table(total))  #table of absences


pander(q1_absences) #pretty table

q1_absences_c <-with(q1_attendance,table(council,total)) #table of absences by council

pander(q1_absences_c) #pretty table
```


```{r total_plot, echo=FALSE}


total_absPlot <- ggplot(q1_attendance,(aes(x =total, y = council)))

total_absPlot + geom_count()



```


# Unexcused
```{r q1_unexcused_tbl, echo=FALSE}

q1_unexcused <-with(q1_attendance,table(unexcused)) #unexcused table

pander(q1_unexcused) #pretty table


q1_unexcused_c <-with(q1_attendance,table(council, unexcused)) #unexcused table by council

pander(q1_unexcused_c) #pretty table

```



# Excused Absences
```{r excused_tbls}
q1_unexcused <-with(q1_attendance,table(excused)) #q1_unexucsed table

pander(q1_unexcused) #make pretty


q1_unexcused_c <-with(q1_attendance,table(council, excused)) #q1_unexcused by council

pander(q1_unexcused_c) #pretty tables

```




