---
title: "Language Arts"
author: "Kevin Gilds, MPA"
date: "December 11, 2016"
output: html_document
---

```{r langarts_libaries, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(pander)
library(ggplot2)
library(sqldf)
library(psych)
library(knitr)
library(gridExtra)
library(effsize)
library(likert)
library(getREAL)

```


```{r langarts_db, echo=FALSE}

setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

### Make connection with database
getRealdb <- dbConnect(SQLite(), dbname="outcome_history.sqlite")


q1_langarts <- dbReadTable(getRealdb,"Q1_langarts_1617")

q1_langarts1516 <-dbReadTable(getRealdb,"Q1_lang_1516")



```


```{r}
head(q1_langarts)

q1_16 <- q1_langarts %>%
    select(girl_code, langarts_course, grade, lang_avg)%>%
    mutate("Year" = "16-17")

head(q1_langarts1516)

q1_15 <- q1_langarts1516 %>%
    select(girlCode, langCourses, langGrade, lang_pts) %>%
    rename(girl_code =girlCode) %>%
    rename(langarts_course = langCourses)%>%
    rename(lang_avg =lang_pts)%>%
    rename(grade = langGrade) %>%
    mutate("Year" = "15-16")


lang_history <- rbind(q1_16, q1_15)

grade_table <- with(lang_history,table(Year, grade))

grade_table


grade_point <- lang_history %>%
    group_by(Year) %>%
    summarise(lang_avg = mean(lang_avg))


grade_point




```



```{r}

grade_tbl <- with(q1_langarts,table(q1_langarts$grade))

pander(grade_tbl)

mean(q1_langarts$lang_avg)
```

```{r grades_q1_hist}

grades_q1 <- ggplot(q1_langarts, aes(x=lang_avg)) 
    grades_q1 + geom_histogram(fill="blue")


```



```{r}

grade_tbl_15 <- with(q1_langarts1516,table(langGrade))

pander(grade_tbl_15)

mean(q1_langarts1516$lang_pts)
```

