---
title: "reading_report"
author: "Kevin Gilds, MPA"
date: "April 9, 2017"
output:
  html_document: default
  github_document: default
---


```{r reading_import_libaries, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(pander)
library(ggplot2)
library(sqldf)
library(psych)
library(knitr)
library(gridExtra)
library(effsize)
library(likert)
library(getREAL)

```


```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

### Make connection with database
getRealdb<- dbConnect(SQLite(), dbname="outcome_history.sqlite")

q1_reading <- dbReadTable(getRealdb,"Q1_reading_1617")

q2_reading <- dbReadTable(getRealdb, "Q2_reading_1617")

dim(q1_reading)

dim(q2_reading)

```

```{r}

#students <- with(q1_reading, tapply(girl_code, reading_pts, mean))

q1_read_avg <- aggregate(reading_pts ~ girl_code + council, data = q1_reading, mean)

q1_read_avg

q2_read_avg <- aggregate(reading_pts ~ girl_code + council, data = q2_reading, mean)

q2_read_avg

```


```{r}

reading_comparisons <- inner_join(q2_read_avg, q1_read_avg, by="girl_code")

reading_comparisons <- reading_comparisons %>%
    rename(Q2_Avg = reading_pts.x)%>%
    rename(Q1_Avg = reading_pts.y)%>%
    rename(council = council.x)%>%
    mutate(diff = Q2_Avg - Q1_Avg) %>%
    mutate("Data_Source" = "Q2-Q1")


dim(reading_comparisons)

head(reading_comparisons)

```

