---
title: "Status Report"
author: "Kevin Gilds, MPA"
date: '`r Sys.Date()`'
output:
  github_document: default
  html_document: default
  pdf_document:
    latex_engine: xelatex
---


### Data downloaded on: 05/06/2017



### Report Run time:
```{r status_library, echo=FALSE}
library(pander)
```


```{r system_time, echo=FALSE}
pander(Sys.time())
```


### Survey Data Entry Status
```{r echo=FALSE, message=FALSE, warning= FALSE}
library(sqldf)
library(dplyr)
library(dplyr)
library(pander)
library(ggplot2)


setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")


```

```{r pre_student, echo=FALSE, message=FALSE, warning=FALSE}


### Make connection with database
pre_girl <- dbReadTable(getReal_db, "girl_pre_1617")

###Select the neeeded data for data entry status update
pre_girl <- select(pre_girl, council)
###Create and add column for status update



pre_girl$dataSource <-"Pre-Student"

```


```{r post_girl, echo=FALSE}

###Post Girl

post_girl <-dbReadTable(getReal_db, "girl_post_1617") #read table

post_girl <- post_girl %>%
    select(council) %>%  #select variables
    mutate("dataSource" = "Post Student") #add new column


```

```{r pre_parent, echo=FALSE}

### Make connection with database
pre_parent <-dbReadTable(getReal_db,"pre_parent_1617")
###Select the neeeded data for data entry status update
pre_parent <- select(pre_parent,council)
###Create and add column for status update
pre_parent$dataSource <- "Pre-Parent"


```



```{r post_parent, echo=FALSE}

###Post Parent

post_parent <-dbReadTable(getReal_db, "post_parent_1617") #read table 

post_parent <- post_parent %>%
    select(council) %>%  #select columns
    mutate("dataSource"= "Post Parent") #add colummns



```

```{r pre_teacher, echo=FALSE}
### Make connection with database
pre_teacher <-dbReadTable(getReal_db, "pre_teacher_1617")
###Select the neeeded data for data entry status update
pre_teacher <-select(pre_teacher,council)
###Create and add column for status update
pre_teacher$dataSource <- "Pre Teacher"




```

```{r post_teacher, echo=FALSE}

#Post Teacher

post_teacher <-dbReadTable(getReal_db, "post_teacher_1617") #read table from database

post_teacher <- post_teacher %>%
    select(council) %>%
    mutate("dataSource"= "Post Teacher")


```


```{r grades_q1, echo=FALSE}

q1 <- dbReadTable(getReal_db, "Q1_attendance_1617")

q1 <- q1 %>%
    select(council) %>%
    mutate("dataSource" = "Q1")



```

```{r echo=FALSE}
q2 <- dbReadTable(getReal_db, "Q2_attendance_1617")

q2 <- q2 %>%
    select(council) %>%
    mutate("dataSource" = "Q2")

```


```{r counts, echo=FALSE}
##### Geyset counts of Pre and Post Surveys
girl <- nrow(pre_girl) + nrow(post_girl)

#class(girl)
parent <- nrow(pre_parent) + nrow(post_parent)
teacher <- nrow(pre_teacher) + nrow(post_teacher)

```

```{r total_survey_count, echo=FALSE}
Data_Entry<- c(girl, parent, teacher)

Data_Source <- c("Student", "Parent", "Teacher")

total_survey_count <- data.frame(Data_Source, Data_Entry)


```

# Survey Data
```{r survey_status, echo=FALSE}
### Add the teacher to binding for status report

girl_parent <- rbind(pre_girl,pre_parent)



survey_status <- rbind(girl_parent, pre_teacher) #add teacher survey

survey_status <- rbind(survey_status, post_girl)

survey_stauts <- rbind(survey_status, post_teacher)

survey_stauts <- rbind(survey_status, post_parent)
#survey_status <- rbind(survey_status, q1) #add q1


#survey_status <- rbind(survey_status, q2) #add q2


```



```{r echo=FALSE}

grade_status <- rbind(q1, q2)


```


```{r survey_stats, echo=FALSE}

survey_status3 <- with(survey_status,table(dataSource))

survey_status3 <- addmargins(survey_status3)

pander(survey_status3)

saveRDS(survey_status, "data_entry_stat.rds")





```

# Academic Data
```{r echo=FALSE}
grade_status3 <- with(grade_status,table(dataSource)) #table for academic data

pander(grade_status3) #display table

```


### Survey Data Entry Status by Council
```{r council, survey_status, echo=FALSE}

survey_status2 <-with(survey_status,table(council, dataSource))

survey_status2 <- addmargins(survey_status2)

pander(survey_status2)



#barplot(survey_status2)

```

# Academic Data Entry Status by Council
```{r echo=FALSE}
grade_status4 <-with(grade_status,table(council, dataSource)) #table by data entry status and council

survey_status4 <- addmargins(grade_status4) #add margins sum

pander(survey_status4) #diplay table
```


### Duplicate Entries

```{r student_dupes, echo=FALSE}

student_dupes <- dbReadTable(getReal_db, "girl_pre_duplicates_1617")

student_dupes <- student_dupes %>%
    select(council) %>%
    mutate("data_Source" = "Student_dupes")

```


```{r parent_dupes, echo=FALSE}

parent_dupes <- dbReadTable(getReal_db, "pre_parent_duplicate_1617")

parent_dupes <- parent_dupes %>%
    select(council) %>%
    mutate("data_Source" = "Parent_dupes")

```


```{r teacher_dupes, echo=FALSE}

teacher_dupes <- dbReadTable(getReal_db, "pre_teacher_dups_1617")

teacher_dupes <- teacher_dupes %>% 
    select(council) %>%
    mutate("data_Source" = "Teacher_dupes")





```


```{r q1_dupes, echo=FALSE}

q1_dupes <- dbReadTable(getReal_db, "Q1_duplicates_1617")

q1_dupes <- q1_dupes %>%
    select(council) %>%
    mutate("data_Source" = "Q1_dupes")


```

```{r eval=TRUE, echo=FALSE}
q2_dupes <- dbReadTable(getReal_db, "Q2_duplicates_1617")

q2_dupes <- q2_dupes %>%
    select(council) %>%
    mutate("data_Source" = "Q2_dupes")


```


# Survey Duplicate Errors
```{r bind_dupes, echo=FALSE}

student_d_parent_d <- rbind(student_dupes, parent_dupes)

dupe_status <- rbind(student_d_parent_d, teacher_dupes)



```


```{r dupe_status, echo=FALSE}

dupe_status_r <-with(dupe_status,table(data_Source))

dupe_status_r <- addmargins(dupe_status_r)

pander(dupe_status_r)

```



### Duplicate Survey Entries by Council
```{r dupe_status_council, echo=FALSE}

dupe_status_c <-with(dupe_status,table(council,data_Source))

dupe_status_c <- addmargins(dupe_status_c)

pander(dupe_status_c)

```

# Academic Data Duplicate Errors
```{r grade_dupe_setup, echo=FALSE}
grade_dupes <- rbind(q1_dupes, q2_dupes)


```

```{r grade_dupe_tbl, echo=FALSE}
grade_dupes_tbl <- with(grade_dupes,table(data_Source))
```


```{r}
grade_dupes_c <- with(grade_dupes,table(council, data_Source))

grade_dupes_c
```

```{r echo=FALSE, eval=FALSE}
saveRDS(pre_girl, file="pre_girl.rds")
saveRDS(post_girl, file="post_girl.rds")
saveRDS(pre_parent, file="pre_parent.rds")
saveRDS(post_parent, file="post_parent.rds")

```


