---
title: "Coorelations"
author: "Kevin Gilds, MPA"
date: "September 1, 2016"
output: html_document
---


```{r echo=FALSE, warning=FALSE, message=FALSE}


library(sqldf)
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")

library(dplyr)
library(pander)
library(ggplot2)
library(effsize)
library(knitr)

```

```{r read_databases}
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

hr <-dbReadTable(getReal_2016db,"hr_history")

ae <-dbReadTable(getReal_2016db,"ae_history")

am <-dbReadTable(getReal_2016db,"am_history")





```

```{r}
names(hr)
names(ae)
names(am)
```

```{r}
hr_post <- hr %>%
    select(Post) %>%
    rename(hr =Post)

ae_post <- ae %>%
    select(Post) %>%
    rename(ae =Post)

am_post <- am %>%
    select(Post) %>%
    rename(am =Post)



```

```{r}
post_1 <- cbind(hr_post, ae_post)

post_2 <- cbind(post_1, am_post)

head(post_2)



```

```{r coorelations}
cor(post_2)

```

```{r cor_test}
cor.test(post_2$hr, post_2$ae)

cor.test(post_2$hr, post_2$am)

cor.test(post_2$ae, post_2$am)


```

```{r cor_test_ae}

```



```{r coorelation_matrix}

pairs(~hr+ae+am, data=post_2)



```




```{r }
cor(hr_post, ae_post)


plot(hr_post$Post, ae_post$Post)


cor.test(hr_post$Post, ae_post$Post)



```


