---
title: "Get REAL! History"
runtime: shiny
output: flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(sqldf)
library(plotly)
library(ggvis)


hr <- readRDS("hr_history.rds")



ae <- readRDS("ae_history.rds")

am <- readRDS("am_history.rds")

```




Life Skills  



-----------------------------------------------------------------------

Healthy Relationships
=====================================  

### Healthy Relationships: 


```{r}
year_id_hr <- hr %>%
    group_by(Year_Id)

year_id_hr <- summarize(year_id_hr, hr.diff = mean(hr.diff))



year_id_hr$Year_Id <- as.factor(year_id_hr$Year_Id)

#summary(year_id_hr)

ggplot(year_id_hr, aes(y=hr.diff, x=Year_Id, group=2)) + geom_line() + geom_point() + labs (x=" Membership Year", y= "Average Difference ", title="Healthy Relationships: Average Difference Between Pre and Post" )



#p <- plot_ly(year_id_hr, x = ~Year_Id, y = ~hr.diff, type = 'scatter', mode = 'lines')



#qvis(year_id_hr, ~Year_Id, y= ~hr.diff, layers = c("line", "point"))

#qvis(year_id_hr, ~Year_Id, ~hr.diff, layers ="point")
#qvis(mtcars, ~wt, ~mpg, layers = "point")

#ggvis(year_id_hr(x=~Year_Id, y = ~hr.diff)) + layer_line() + mark_point()

# qvis(pressure, ~temperature, ~pressure, layers = c("line", "point"))
#ggvis(pressure, props(x = ~temperature, y = ~pressure)) +
  #layer_line() +
  #mark_point()

hr_avg <- hr %>%
    group_by(Year_Id) %>%
    summarise(Post =mean(Post))

ggplot(hr_avg, aes(y=Post, x=Year_Id, group=2)) + geom_line() + geom_point()+ scale_y_continuous(limit= c(4.45,5)) + labs(x="Membership Year", y="Post Average", title="Healthy Relationships: Post Survey Averages by Year")


```



Academic Engagement
=====================================  


### Academic Engagment



```{r}
year_id_ae <- ae %>%
    group_by(Year_Id)

year_id_ae <- summarize(year_id_ae, ae.diff = mean(ae.diff))

#pander(year_id_ae)

year_id_ae$Year_Id <- as.factor(year_id_ae$Year_Id)

#summary(year_id_ae)



ggplot(year_id_ae, aes(y=ae.diff, x=Year_Id, group=2)) + geom_line() + geom_point() + labs (x="Membership Year", y= "Average Difference ", title="Academic Engagement: Average Difference Between Pre and Post" )



ae_avg <- ae %>%
    group_by(Year_Id) %>%
    summarise(Post =mean(Post))

ggplot(ae_avg, aes(y=Post, x=Year_Id, group=2)) + geom_line() + geom_point() + labs(x="Membership Year", y="Post Average", title="Academic Engagement: Post Survey Averages by Year")





```


-----------------------------------------------------------------------


Academic Mastery
=====================================  


### Academic Mastery



```{r}
year_id_am <- am %>%
    group_by(Year_Id)

year_id_am <- summarize(year_id_am, am.diff = mean(am.diff))

#pander(year_id_am)

year_id_am$Year_Id <- as.factor(year_id_am$Year_Id)

#summary(year_id_am)



ggplot(year_id_am, aes(y=am.diff, x=Year_Id, group=2)) + geom_line() + geom_point() + labs (x="Membership Year", y= "Average Difference", title="Academic Mastery: Average Difference Between Pre and Post")


am_avg <- am %>%
    group_by(Year_Id) %>%
    summarise(Post =mean(Post))

ggplot(am_avg, aes(y=Post, x=Year_Id, group=2)) + geom_line() + geom_point() + labs(x="Membership Year", y="Post Average", title="Academic Mastery: Post Survey Averages by Year")


```



`

