---
title: "Healthy Relationship History"
author: "Kevin Gilds, MPA"
date: "September 1, 2016"
output:
  github_document: default
  html_document: default
  pdf_document: default
---

```{r echo=FALSE, warning=FALSE, message=FALSE}


library(sqldf)
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")

library(DT)
library(getREAL)
library(dplyr)
library(pander)
library(ggplot2)
library(effsize)
library(knitr)
library(catspec)
library(formattable)

```


```{r read_databases_hr, echo=FALSE}
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

hr <-dbReadTable(getReal_2016db,"hr_history")

#dim(hr)

hr_unique<- hr [!(duplicated(hr$girlCode) | duplicated(hr$girlCode, fromLast = TRUE)), ] #find and subset uniquie students

hr_unique <- hr_unique %>% 
    mutate("Match" = "No") # Add in variable and response

#dim(hr_unique)

hr_dupes <-duplicated(hr$girlCode) | duplicated(hr$girlCode, fromLast=TRUE) #find duplicated cases

hr_dupes <- hr[hr_dupes, ] # subset dupes

#dim(hr_dupes)

hr_dupes <- hr_dupes %>%
    mutate("Match" = "Yes") #add variable and response


hr <- rbind(hr_dupes, hr_unique)






```


```{r council_names_hr, echo=FALSE}
## Change council names to be consistent wiht how they displayed with the surveys
hr$council <-sub("Girl Scouts of the Gateway Council", "Gateway Council", fixed=TRUE, hr$council)

hr$council <-sub("Girl Scouts of Citrus Council", "Citrus Council", fixed=TRUE, hr$council)

hr$council <-sub("Girl Scouts of Southeast Florida", "Southeast Council", fixed=TRUE, hr$council)

hr$council <-sub("Southeast Council, Inc", "Southeast Council", fixed=TRUE, hr$council)

hr$council <-sub("Southeast Council.", "Southeast Council", fixed=TRUE, hr$council)

hr$council <-sub("Girl Scout Council of Tropical Florida", "Tropical Council", fixed = TRUE, hr$council)

hr$council <-sub("Girl Scouts of West Central Florida", "West Central Council", fixed = TRUE, hr$council)

hr$council <-sub("Girl Scout Council of the Panhandle", "Panhandle Council", fixed = TRUE, hr$council)

hr$council <-sub("Girl Scouts of Gulfcoast Florida Inc.",  "Gulfcoast Council", fixed = TRUE, hr$council)

```

```{r update_year_hr, echo=FALSE}
hr$Year_Id <-sub("M1",  "13-14", fixed = TRUE, hr$Year_Id)

hr$Year_Id <-sub("M2",  "14-15", fixed = TRUE, hr$Year_Id)

hr$Year_Id <-sub("M3",  "15-16", fixed = TRUE, hr$Year_Id)


```

```{r succes_hr, echo=FALSE}
hr_1 <- hr %>%
    filter(Post >=4.45)%>%
    mutate("Success" = "TRUE")

#dim(hr_1)

hr_2 <- hr %>%
    filter(Post <4.45 & hr.diff >0)%>%
    mutate("Success" = "TRUE")



#dim(hr_2)

hr_3 <- hr %>%
    filter(Post < 4.45 & hr.diff <=0)%>%
    mutate("Success" = "FALSE")

#dim(hr_3)

hr_1 <- rbind(hr_1, hr_2)

hr <- rbind(hr_1, hr_3)

#head(hr)

#hr_f <- hr %>%
    #filter(Success ==FALSE)

#head(hr_f)
#tail(hr_f)

```



# Healthy Relationships


## Post Survey Success


```{r hr_suc, echo=FALSE}
hr_suc <- hr %>%
    count(Success)%>%
    mutate(percent = n/sum(n))

hr_suc$percent <- percent(hr_suc$percent)

kable(hr_suc)

```


### Achievement by Council

```{r council_hr, echo=FALSE}

council_hr <- hr %>%
    group_by(council) %>%
    count(Success) %>%
    mutate(percent = n / sum(n))


council_hr$percent <- percent(council_hr$percent)

council_hr <- council_hr %>%
    filter(Success == TRUE)

kable(council_hr)

#achieved_hr_post <- with(council_hr, table(council, Post >= 4.45))

#achieved_hr_post <-prop.table(achieved_hr_post,1)

#achieved_hr_post<-round(achieved_hr_post*100,2)



#pander(achieved_hr_post)

```

### Achievement by Matched Status 

```{r post_hr_1, echo=FALSE}
match_hr <- hr %>%
    group_by(Match) %>%
    count(Success) %>%
    mutate(percent = n /sum(n))

match_hr$percent <- percent(match_hr$percent)



kable(match_hr)
```


## Average Difference between Pre and Post Surveys

The mean difference between pre and post survey is `r pander(mean(hr$hr.diff))`. 


```{r hr_diff_m, echo=FALSE}
hr_diff_m <- hr %>%
    group_by(Match) %>%
    summarise(mean= mean(hr.diff)) 
    
kable(hr_diff_m)

```





```{r hr_change_p, echo=FALSE, fig.path='Figs/'}
healthy_change_p <- ggplot(hr,(aes(x=hr.diff, y=council)))
healthy_change_p + geom_count() + geom_vline(xintercept = 0, col="red") + labs(x="Pre and Post Difference", y="Council", title="Healthy Releationship Survey Results")


```

### Average Difference by Year

```{r hr_diff_y, echo=FALSE, fig.path='Figs/'}
year_id_hr <- hr %>%
    group_by(Year_Id)

year_id_hr <- summarize(year_id_hr, hr.diff = mean(hr.diff))

pander(year_id_hr)

year_id_hr$Year_Id <- as.factor(year_id_hr$Year_Id)

#summary(year_id_hr)

ggplot(year_id_hr, aes(y=hr.diff, x=Year_Id, group=2)) + geom_line() + geom_point() + labs (x="Year", y= "Difference Pre and Post", title="Difference Pre and Post Healthy Relationships" )

```



### Average Difference between Pre and Post by Council

```{r diff_council, echo=FALSE}
council_hr <- hr %>%
    group_by(council)

council_hr_c <-summarise(council_hr, hr.diff =mean(hr.diff))

pander(council_hr_c)



```



```{r council_hr_c, echo=FALSE, eval=FALSE}
council_hr <- hr %>%
    group_by(council, Year_Id)

council_hr_diff <-summarise(council_hr, hr.diff =mean(hr.diff))

pander(council_hr_diff)

datatable(council_hr_diff)

```



```{r plot_density, echo=FALSE, eval=FALSE}





hist(hr$hr.diff, col="red", freq=FALSE)
hr_dent <- density(hr$hr.diff)
lines(hr_dent)



```


```{r qnorm, echo=FALSE, eval=FALSE}

qqnorm(hr$hr.diff)
qqline(hr$hr.diff, col = 2)

```


```{r shapiro.test_hr, echo=FALSE, eval=FALSE}
shapiro.test(hr$hr.diff)
```



```{r t_test_hr, echo=FALSE, eval=FALSE}
t.test(hr$Pre, hr$Post)



cohen.d(hr$Pre, hr$Post)
```














```{r post_council, echo=FALSE, eval=FALSE}


council_hr_test <-council_hr %>%
    group_by(council,Year_Id) %>%
    count(Post >=4.45)

datatable(council_hr_test)

```



## Post Survey Average Score


```{r hr_avg, echo=FALSE}
hr_avg <- hr %>%
    group_by(Year_Id) %>%
    summarise(Post =mean(Post))

pander(hr_avg)

```

```{r hr_avg-m, echo=FALSE}
hr_avg_m <- hr %>%
    group_by(Match)%>%
    summarise(Post =mean(Post))

kable(hr_avg_m)
```





```{r hr_post_avg, echo=FALSE, fig.path='Figs/'}
ggplot(hr_avg, aes(y=Post, x=Year_Id, group=2)) + geom_line() + geom_point()+ scale_y_continuous(limit= c(4.45,5)) + labs(x="Membership Year", y="Post Average", title="Healthy Relationships Post Survey Averages by Year")




```



```{r council_hr_post_tbl, echo=FALSE, eval=FALSE}


head(council_hr)

council_hr_post <-summarise(council_hr, Post =mean(Post))

pander (council_hr_post)

```



```{r achieved_pr, echo=FALSE, eval=FALSE}
achieved_hr <- with(council_hr, table(council, Pre >= 4.45))

achieved_hr

achieved_hr_p <-prop.table(achieved_hr,1)

achieved_hr_p<-round(achieved_hr_p*100,2)

pander(achieved_hr_p)
```


```{r council_pre, echo=FALSE, eval=FALSE}
council_hr_pre <-summarise(council_hr, Pre =mean(Pre))


datatable(council_hr_pre, rownames = FALSE)


```


```{r updated hr to db, echo=FALSE}

setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")

### Write hr_history data to sqlite database
dbWriteTable(conn = getReal_2016db, name = "hr_history", value = hr, row.names=FALSE, overwrite=TRUE)

```


