---
title: "language_arts_history"
author: "Kevin Gilds, MPA"
date: "September 24, 2016"
output: html_document
---


```{r echo=FALSE, warning=FALSE, message=FALSE}


library(sqldf)
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")

library(DT)
library(getREAL)
library(dplyr)
library(pander)
library(ggplot2)
library(effsize)
library(knitr)
library(catspec)

```

```{r}
lang_1516 <-dbReadTable(getReal_2016db, "langarts_1516")

lang_1516 <- lang_1516 %>%
    select(council, 1:4,6) %>%
    mutate("Year_Id" = "M3")
    


```

```{r}

setwd("C:/Users/kevin/Dropbox/GetReal/Reports/MY-2014-2015/Summ Evaluation Report/data")

getReal_2015db<- dbConnect(SQLite(), dbname="data_Final_GetReal_2014_2015.sqlite")


#lang_1415 <- readRDS("langarts_final.RDS")

#dim(lang_1415)

#head(lang_1415)




lang_1415 <-dbReadTable(getReal_2015db, "langarts_final_matched")



lang_1415 <- lang_1415%>% 
    select(girlCode,council.x, q4Grade, q1Grade, langDiff) %>%
    rename(council = council.x, final = q4Grade, baseline = q1Grade, Grade_Change =langDiff) %>%
    mutate("Year_Id" = "M2")

```



```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Analyis_data")

getReal_2014db<- dbConnect(SQLite(), dbname="getReal.sqlite")

lang_1314 <-dbReadTable(getReal_2014db, "langArtsFinal")



```

```{r}
three_14 <- lang_1314[grep("^314", lang_1314$girlCode),]



three_14 <- three_14 %>%
    mutate("council" = "Gulfcoast Council") %>%
    mutate("langdiff" = finish - start)

```



```{r}

three_13 <- lang_1314[grep("^313", lang_1314$girlCode),]



three_13 <-three_13 %>% 
    mutate("council" = "Gateway Council") %>%
    mutate("langdiff" = finish- start)


```

```{r}

three_20 <- lang_1314[grep("^320", lang_1314$girlCode),]


three_20 <- three_20 %>%
    mutate("council" = "West Central Council") %>%
    mutate("langdiff" = finish - start)


```


```{r}
three_21 <- lang_1314[grep("^321", lang_1314$girlCode),]


three_21 <- three_21 %>%
    mutate("council" = "Southeast Council") %>%
    mutate("langdiff" = finish - start)


```


```{r}

three_22 <- lang_1314[grep("^322", lang_1314$girlCode),]


three_22 <- three_22 %>%
    mutate("council" = "Pandhandle Council") %>%
    mutate("langdiff" = finish - start)
   

```


```{r}

gateway_gulf <- rbind(three_13, three_14)

wcf <- rbind(gateway_gulf, three_20)

southeast <- rbind(wcf, three_21)

lang_1314_a <- rbind(southeast, three_22)

dim(lang_1314_a)

lang_1314_a <- lang_1314_a %>%
    mutate("Year_Id" = "M1") %>%
    rename(baseline = start, final = finish, Grade_Change = langdiff)

```

```{r}
head(lang_1516)
head(lang_1415)
head(lang_1314_a)

```

```{r}
lang_1516 <- lang_1516[,c(2,1,6,3,4,5)]
#df2[,c(1,3,2,4)]

head(lang_1516)

```



```{r}
lang_1314_a<-lang_1314_a[,c(1,4, 6,2,3,5)]
#df2[,c(1,3,2,4)]

head(lang_1314_a)

```

```{r}
lang_1415 <- lang_1415[,c(1,2,6, 4, 3, 5)]

head(lang_1415)

```

```{r}

lang_1 <-rbind(lang_1314_a, lang_1415)

lang_history <- rbind(lang_1, lang_1516)

dim(lang_history)






```

```{r}
summary(lang_history)
```



```{r}
lang_history_filtered <- lang_history %>%
    filter(baseline !=4 | final != 4)

summary(lang_history_filtered$Grade_Change)


hist(lang_history_filtered$Grade_Change)


```


```{r}

t.test(lang_history$baseline, lang_history$final)

cohen.d(lang_history$baseline, lang_history$final)

```


Tests with filtered data
```{r}

t.test(lang_history_filtered$baseline, lang_history_filtered$final)

cohen.d(lang_history_filtered$baseline, lang_history_filtered$final)

```

