---
title: "matched_survey_history"
author: "Kevin Gilds, MPA"
date: "September 1, 2016"
output: html_document
---

```{r echo=FALSE, warning=FALSE, message=FALSE}


library(sqldf)
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")

library(DT)
library(getREAL)
library(dplyr)
library(pander)
library(ggplot2)
library(effsize)
library(knitr)

```


```{r read_databases}
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

hr <-dbReadTable(getReal_2016db,"hr_history")

ae <-dbReadTable(getReal_2016db,"ae_history")

am <-dbReadTable(getReal_2016db,"am_history")


```


```{r}
## Change council names to be consistent wiht how they displayed with the surveys
hr$council <-sub("Girl Scouts of the Gateway Council", "Gateway Council", fixed=TRUE, hr$council)

hr$council <-sub("Girl Scouts of Citrus Council", "Citrus Council", fixed=TRUE, hr$council)

hr$council <-sub("Girl Scouts of Southeast Florida", "Southeast Council", fixed=TRUE, hr$council)

hr$council <-sub("Southeast Council, Inc", "Southeast Council", fixed=TRUE, hr$council)

hr$council <-sub("Southeast Council.", "Southeast Council", fixed=TRUE, hr$council)

hr$council <-sub("Girl Scout Council of Tropical Florida", "Tropical Council", fixed = TRUE, hr$council)

hr$council <-sub("Girl Scouts of West Central Florida", "West Central Council", fixed = TRUE, hr$council)

hr$council <-sub("Girl Scout Council of the Panhandle", "Panhandle Council", fixed = TRUE, hr$council)

hr$council <-sub("Girl Scouts of Gulfcoast Florida Inc.",  "Gulfcoast Council", fixed = TRUE, hr$council)

```

# Introduction

Matching survey data set from the past three membership years.

* M1 = MY: 2013-2014

* M2 = MY: 2014-2015

* M3 = MY: 2015-2016

```{r}
council_status <- with(hr,table(council, Year_Id))

pander(council_status)

```



# Life Skills Outcome

## Healthy Relationships Life Skills

### Post Survey Healthy Relationships

```{r}
council_hr <- hr %>%
    group_by(council, Year_Id)

```

```{r}
achieved_hr_post <- with(council_hr, table(council, Post >= 4.45))

achieved_hr_post

achieved_hr_post <-prop.table(achieved_hr_post,1)

achieved_hr_post<-round(achieved_hr_post*100,2)

pander(achieved_hr_post)

```


```{r}


head(council_hr)

council_hr_post <-summarise(council_hr, Post =mean(Post))

datatable (council_hr_post)


```

```{r}
achieved_hr <- with(council_hr, table(council, Pre >= 4.45))

achieved_hr

achieved_hr_p <-prop.table(achieved_hr,1)

achieved_hr_p<-round(achieved_hr_p*100,2)

pander(achieved_hr_p)
```



### Pre Surveys

```{r}
council_hr_pre <-summarise(council_hr, Pre =mean(Pre))


datatable(council_hr_pre)


```



